spring:
  config:
    activate:
      on-profile: qa

loans:
  message: "Welcome to QA Loans Service"
  contactDetails:
    name: "Lee xin cheng"
    email: "duadhahdwdhudwhu@gmail.com"
  onCallSupport:
    - 0399222222
    - 0399333333