server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:localStorage
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: qa

build:
  version: 1.0.0

accounts:
  message: "Welcome to my account service"
  contactDetails:
    name: "Thang"
    email: "yywdijdiwdi@gmail.com"
  onCallSupport:
    - 0399222222
    - 0399333333