server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3312/cardsdb
    hikari:
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071"
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  docker run --name cardsdb -p 3312:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=carsdb -d mysql
