services:
  network-deploy-service:
    networks:
      - ms

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  microservice-service-config:
    extends:
      service: microservice-base-config
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071
      - SPRING_PROFILES_ACTIVE=default