spring:
  config:
    activate:
      on-profile: qa
cards:
  message: "Welcome to QA my card service"

  contactDetails:
    name: "LEE JONGO SUK"
    email: "daiwidiwjdhuwh.com"

  onCallSupport:
    - 0399222222
    - 0399333333