services:
  accounts-service:
    image: hogiathang/accounts:v1
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 800M
    networks:
      - ms
  loans-service:
    image: hogiathang/loans:v1
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 800M
    networks:
      - ms
  cards-service:
    image: hogiathang/cards:v1
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 800M
    networks:
      - ms
networks:
  ms:
    driver: bridge