server:
  port: 8080
spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 10000
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 2s
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
  endpoint:
    gateway:
      access:
        enabled: true

info:
  app:
    name: gatewayserver
    description: "Gateway Service"
    version: 5.2

logging:
  level:
    com:
      hogiathang:
        gatewayserver: DEBUG
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000