server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3311/loansdb
    hikari:
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071"
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"