spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/RavenTheshadow/micro_config.git"
          default-label: master
          timeout: 10
          clone-on-start: true
          force-pull: true
          username: RavenTheshadow
          password: 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
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
    # RabbitMQ configuration # latest RabbitMQ 4.0.x
    # docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true