server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3310/accountsdb
    hikari:
      username: root
      password: root
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071"
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"