spring:
  config:
    activate:
      on-profile: prod

cards:
  message: "Welcome to production my card service"

  contactDetails:
    name: "LEE JONGOUUWUU SUUWUHUDK"
    email: "daiwidiwjdhudwdawdawh.com"

  onCallSupport:
    - 0399222222
    - 0399333333