spring:
  application:
    name: configServer
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/RavenTheshadow/micro_config.git"
          default-label: master
          timeout: 10
          clone-on-start: true
          force-pull: true
          username: RavenTheshadow
          password: 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
  #        native:
#          search-locations: "file:///C:/Users/MyClone/OneDrive/Desktop/MicroserviceCourse/B6/v2-springCloudConfig/configuration"
#          search-locations: "classpath:/config"
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
server:
  port: 8071

encrypt:
  key: "4FEI0J9KJL45JBB134256"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # /actuator/health
  endpoint:
    health:
      probes:
        enabled: true