spring:
  application:
    name: configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C:/Users/MyClone/OneDrive/Desktop/MicroserviceCourse/B6/v2-springCloudConfig/configuration"
#          search-locations: "classpath:/config"
server:
  port: 8071
